# Generated by Django 2.0.6 on 2018-07-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_room_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='title',
            new_name='text',
        ),
    ]
