# Generated by Django 2.1.1 on 2018-09-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_room_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
    ]
