# Generated by Django 2.1.1 on 2018-09-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_auto_20180925_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.TextField(null=True),
        ),
    ]
